### ISSUE TITLE
Evaluation gets stuck with jenatdb2

### ISSUE THREAD

**Issue by GreenfishK** [GreenfishK/BEAR#12]
After sucessfully executing **jenatdb2, cb_sr_ng, bearc**  and **jenatdb2, cb_sr_ng, bearb_hour** the evaluation process gets stuck with **jenatdb2, cb_sr_ng, bearb_day**

**Comment by GreenfishK** [comment]
Stack trace from docker logs
```
[2023-02-01 21:13:24] Server     INFO  Apache Jena Fuseki 4.0.0
[2023-02-01 21:13:24] Config     INFO  FUSEKI_HOME=/jena-fuseki
[2023-02-01 21:13:24] Config     INFO  FUSEKI_BASE=/run
[2023-02-01 21:13:24] Config     INFO  Shiro file: file:///run/shiro.ini
[2023-02-01 21:13:24] Config     INFO  Configuration file: /run/config.ttl
[2023-02-01 21:13:24] Config     INFO  Load configuration: file:///run/configuration/cb_sr_ng_bearb_hour.ttl
[2023-02-01 21:13:25] Server     ERROR Exception in initialization: caught: Failed to get a lock: file='/starvers_eval/databases/jenatdb2/cb_sr_ng_bearb_hour/cb_sr_ng_bearb_hour/tdb.lock': held by process 318
[2023-02-01 21:13:25] WebAppContext WARN  Failed startup of context o.e.j.w.WebAppContext@2cd4e16a{Apache Jena Fuseki Server,/,file:///jena-fuseki/webapp/,UNAVAILABLE}
org.apache.jena.assembler.exceptions.AssemblerException: caught: Failed to get a lock: file='/starvers_eval/databases/jenatdb2/cb_sr_ng_bearb_hour/cb_sr_ng_bearb_hour/tdb.lock': held by process 318
        at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.openBySpecificType(AssemblerGroup.java:165) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.open(AssemblerGroup.java:144) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.assembler.assemblers.AssemblerGroup$ExpandingAssemblerGroup.open(AssemblerGroup.java:93) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.assembler.assemblers.AssemblerBase.open(AssemblerBase.java:39) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.assembler.assemblers.AssemblerBase.open(AssemblerBase.java:35) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.build.FusekiConfig.getDataset(FusekiConfig.java:687) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.build.FusekiConfig.buildDataService(FusekiConfig.java:444) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.build.FusekiConfig.buildDataAccessPoint(FusekiConfig.java:434) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.build.FusekiConfig.readConfiguration(FusekiConfig.java:417) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.build.FusekiConfig.readConfigurationDirectory(FusekiConfig.java:396) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.webapp.FusekiWebapp.initializeDataAccessPoints(FusekiWebapp.java:220) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.webapp.FusekiServerListener.serverInitialization(FusekiServerListener.java:97) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.webapp.FusekiServerListener.contextInitialized(FusekiServerListener.java:57) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:426) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.Server.start(Server.java:423) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.Server.doStart(Server.java:387) [fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.JettyFusekiWebapp.start(JettyFusekiWebapp.java:125) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd.runFuseki(FusekiCmd.java:376) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.exec(FusekiCmd.java:360) [fuseki-server.jar:4.0.0]
        at org.apache.jena.cmd.CmdMain.mainMethod(CmdMain.java:92) [fuseki-server.jar:4.0.0]
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:58) [fuseki-server.jar:4.0.0]
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:45) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.innerMain(FusekiCmd.java:105) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd.main(FusekiCmd.java:68) [fuseki-server.jar:4.0.0]
Caused by: org.apache.jena.dboe.DBOpEnvException: Failed to get a lock: file='/starvers_eval/databases/jenatdb2/cb_sr_ng_bearb_hour/cb_sr_ng_bearb_hour/tdb.lock': held by process 318
        at org.apache.jena.dboe.base.file.ProcessFileLock.lockOperation(ProcessFileLock.java:199) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.dboe.base.file.ProcessFileLock.lockEx(ProcessFileLock.java:125) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.tdb2.sys.DatabaseConnection.build(DatabaseConnection.java:100) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.tdb2.sys.DatabaseConnection.lambda$make$0(DatabaseConnection.java:74) ~[fuseki-server.jar:4.0.0]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:?]
        at org.apache.jena.tdb2.sys.DatabaseConnection.make(DatabaseConnection.java:74) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.tdb2.sys.DatabaseConnection.connectCreate(DatabaseConnection.java:63) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.tdb2.sys.DatabaseConnection.connectCreate(DatabaseConnection.java:54) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.tdb2.DatabaseMgr.DB_ConnectCreate(DatabaseMgr.java:41) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.tdb2.DatabaseMgr.connectDatasetGraph(DatabaseMgr.java:46) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.tdb2.assembler.DatasetAssemblerTDB.make(DatasetAssemblerTDB.java:59) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.tdb2.assembler.DatasetAssemblerTDB.createDataset(DatasetAssemblerTDB.java:50) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.sparql.core.assembler.DatasetAssembler.open(DatasetAssembler.java:43) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.openBySpecificType(AssemblerGroup.java:157) ~[fuseki-server.jar:4.0.0]
        ... 42 more
[2023-02-01 21:13:25] Server     ERROR SPARQLServer: Failed to start server: Failed to bind to 0.0.0.0/0.0.0.0:3030
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:3030
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.JettyFusekiWebapp.start(JettyFusekiWebapp.java:125) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd.runFuseki(FusekiCmd.java:376) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.exec(FusekiCmd.java:360) [fuseki-server.jar:4.0.0]
        at org.apache.jena.cmd.CmdMain.mainMethod(CmdMain.java:92) [fuseki-server.jar:4.0.0]
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:58) [fuseki-server.jar:4.0.0]
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:45) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.innerMain(FusekiCmd.java:105) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd.main(FusekiCmd.java:68) [fuseki-server.jar:4.0.0]
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[?:?]
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[?:?]
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[fuseki-server.jar:4.0.0]
        ... 14 more
```

**Comment by GreenfishK** [comment]
With every evaluation scenario the respective config file was copied into /run/configuration but config files from previous scenarios were not deleted. 
I changed this now by overwriting the config files
```cp /starvers_eval/configs/jenatdb2/${policy}_${dataset}.ttl /run/configuration/config.ttl```

**Comment by GreenfishK** [comment]
New error
```
[2023-02-02 10:25:12] Server     ERROR SPARQLServer: Failed to start server: Failed to bind to 0.0.0.0/0.0.0.0:3030
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:3030
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[fuseki-server.jar:4.0.0]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.JettyFusekiWebapp.start(JettyFusekiWebapp.java:125) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd.runFuseki(FusekiCmd.java:376) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.exec(FusekiCmd.java:360) [fuseki-server.jar:4.0.0]
        at org.apache.jena.cmd.CmdMain.mainMethod(CmdMain.java:92) [fuseki-server.jar:4.0.0]
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:58) [fuseki-server.jar:4.0.0]
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:45) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd$FusekiCmdInner.innerMain(FusekiCmd.java:105) [fuseki-server.jar:4.0.0]
        at org.apache.jena.fuseki.cmd.FusekiCmd.main(FusekiCmd.java:68) [fuseki-server.jar:4.0.0]
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[?:?]
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[?:?]
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[fuseki-server.jar:4.0.0]
        ... 14 more
```

**Comment by GreenfishK** [comment]
I added a line that waits until the triple store server is actually killed. This problem seems solved now.
