### ISSUE TITLE
Cannot build in-memory snapshot of graph for Jenatdb2 and cb_sr_ng

### ISSUE THREAD

**Issue by GreenfishK** [GreenfishK/BEAR#16]
Stack trace
```
2023-02-08 Wednesday 13:48:01 root:INFO:Build snapshot version 0363 from endpoint http://Starvers:3030/cb_sr_ng_bearb_hour/sparql
2023-02-08 Wednesday 13:48:20 root:INFO:Shutting down fuseki server and finishing evaluation of cb_sr_ng_bearb_hour.
```

Docker stack trace
```
evaluate_single_1          | Traceback (most recent call last):
evaluate_single_1          |   File "/starvers_eval/scripts/6_evaluate/query.py", line 232, in <module>
evaluate_single_1          |     build_snapshot(snapshot_g)
evaluate_single_1          |   File "/starvers_eval/scripts/6_evaluate/query.py", line 221, in build_snapshot
evaluate_single_1          |     del_set = engine.query().convert()
evaluate_single_1          |   File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 960, in query
evaluate_single_1          |     return QueryResult(self._query())
evaluate_single_1          |   File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 926, in _query
evaluate_single_1          |     response = urlopener(request)
evaluate_single_1          |   File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
evaluate_single_1          |     return opener.open(url, data, timeout)
evaluate_single_1          |   File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
evaluate_single_1          |     response = self._open(req, data)
evaluate_single_1          |   File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
evaluate_single_1          |     result = self._call_chain(self.handle_open, protocol, protocol +
evaluate_single_1          |   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
evaluate_single_1          |     result = func(*args)
evaluate_single_1          |   File "/usr/local/lib/python3.8/urllib/request.py", line 1383, in http_open
evaluate_single_1          |     return self.do_open(http.client.HTTPConnection, req)
evaluate_single_1          |   File "/usr/local/lib/python3.8/urllib/request.py", line 1358, in do_open
evaluate_single_1          |     r = h.getresponse()
evaluate_single_1          |   File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
evaluate_single_1          |     response.begin()
evaluate_single_1          |   File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
evaluate_single_1          |     version, status, reason = self._read_status()
evaluate_single_1          |   File "/usr/local/lib/python3.8/http/client.py", line 285, in _read_status
evaluate_single_1          |     raise RemoteDisconnected("Remote end closed connection without"
evaluate_single_1          | http.client.RemoteDisconnected: Remote end closed connection without response
```

Seems that it is not due to memory overflow

**Comment by GreenfishK** [comment]
for the current evaluation skip this evaluation scenario, i.e. jena tdb2 and cb_sr_ng.
