### ISSUE TITLE
Non-empty DB directories cannot be removed 

### ISSUE THREAD

**Issue by GreenfishK** [GreenfishK/BEAR#18]
During the execution of construct_tb_star_ds I get this error in the second iteration:
```
rm: cannot remove '/starvers_eval/databases/construct_datasets/graphdb/repositories/tb_rs_sr_bearb_day/storage/history': Directory not empty
rm: cannot remove '/starvers_eval/databases/construct_datasets/graphdb/repositories/tb_rs_sr_bearb_day/storage/literals-index': Directory not empty
17:16:59.185 [main] INFO  c.ontotext.graphdb.importrdf.Preload - Input folders recursively: false
17:16:59.187 [main] INFO  c.ontotext.graphdb.importrdf.Preload - Iterator cache set to: 'auto'
17:16:59.187 [main] INFO  c.ontotext.graphdb.importrdf.Preload - Chunk size set to: 'auto'
17:16:59.188 [main] INFO  c.ontotext.graphdb.importrdf.Preload - Parsing tasks: 2
17:16:59.188 [main] INFO  c.ontotext.graphdb.importrdf.Preload - Temporary data folder: /.
17:16:59.190 [main] INFO  c.ontotext.graphdb.importrdf.Preload - Restore point interval: 3,600s
17:16:59.190 [main] INFO  c.ontotext.graphdb.importrdf.Preload - CONFIG FILE: /starvers_eval/configs/construct_datasets/graphdb_tb_rs_sr_bearb_day/graphdb-config.ttl
17:16:59.205 [main] INFO  c.ontotext.graphdb.importrdf.Preload - Attaching to location: /starvers_eval/databases/construct_datasets/graphdb
org.eclipse.rdf4j.repository.RepositoryException: Failed to lock directory: /starvers_eval/databases/construct_datasets/graphdb/repositories. Is another GraphDB instance running?
        at com.ontotext.graphdb.GraphDBRepositoryManager.init(GraphDBRepositoryManager.java:219)
        at com.ontotext.graphdb.importrdf.BaseLoadTool.mainInternal(BaseLoadTool.java:161)
        at com.ontotext.graphdb.importrdf.Preload.call(Preload.java:250)
        at com.ontotext.graphdb.importrdf.Preload.call(Preload.java:53)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.ontotext.graphdb.importrdf.ImportRDF.main(ImportRDF.java:25)
/opt/graphdb/dist/bin/graphdb: line 75: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Exception in thread "main" org.apache.catalina.LifecycleException: Protocol handler initialization failed
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:1051)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:556)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1045)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        at org.apache.catalina.startup.Tomcat.init(Tomcat.java:475)
        at com.ontotext.graphdb.server.GraphDB.start(GraphDB.java:171)
        at com.ontotext.graphdb.server.GraphDBServer.main(GraphDBServer.java:10)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:459)
        at java.base/sun.nio.ch.Net.bind(Net.java:448)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:275)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:230)
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1227)
        at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1240)
        at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:606)
        at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:77)
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:1048)
        ... 8 more
/opt/graphdb/dist/bin/graphdb: line 75: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 926, in _query
    response = urlopener(request)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/starvers_eval/scripts/3_construct_datasets/construct_datasets.py", line 411, in <module>
    construct_tb_star_ds(source_ic0=f"{data_dir}/{snapshot_dir}/" + "1".zfill(ic_basename_lengths[dataset])  + ".nt",
  File "/starvers_eval/scripts/3_construct_datasets/construct_datasets.py", line 145, in construct_tb_star_ds
    rdf_star_engine.insert(triples=added_triples_raw, timestamp=vers_ts, chunk_size=chunk_size)
  File "/starvers_eval/python_venv/lib/python3.8/site-packages/starvers/starvers.py", line 470, in insert
    self.sparql_post.query()
  File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 960, in query
    return QueryResult(self._query())
  File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 932, in _query
    raise EndPointNotFound(e.read())
SPARQLWrapper.SPARQLExceptions.EndPointNotFound: EndPointNotFound: It was not possible to connect to the given endpoint: check it is correct. 
```

**Comment by GreenfishK** [comment]
Solved it by first making sure that the database connection is shutdown.
