### ISSUE TITLE
cannot ingest the BEARC dataset alldata.TB_star_hierarchical.ttl into JenaTDB2

### ISSUE THREAD

**Issue by GreenfishK** [GreenfishK/BEAR#3]
This is a follow-up issue of issue https://github.com/GreenfishK/starvers_eval/issues/1. While ingesting into GraphDB went through without an error, JenaTDB2 is still hanging at 1.500.000 triples.

**Comment by GreenfishK** [comment]
Jena seems to have a practical limit when loading RDF-star triples. This limit is somewhere around 1.6 Mio triples.

**Comment by GreenfishK** [comment]
Seems to be a java heap space problem

```
Exception in thread "Thread-2" java.lang.OutOfMemoryError: Java heap space
        at org.apache.thrift.TUnion$TUnionStandardSchemeFactory.getScheme(TUnion.java:209)
        at org.apache.thrift.TUnion$TUnionStandardSchemeFactory.getScheme(TUnion.java:207)
        at org.apache.thrift.TUnion.write(TUnion.java:152)
        at org.apache.jena.riot.thrift.wire.RDF_Triple$RDF_TripleStandardScheme.write(RDF_Triple.java:534)
        at org.apache.jena.riot.thrift.wire.RDF_Triple$RDF_TripleStandardScheme.write(RDF_Triple.java:468)
        at org.apache.jena.riot.thrift.wire.RDF_Triple.write(RDF_Triple.java:397)
        at org.apache.jena.riot.thrift.wire.RDF_Term.standardSchemeWriteValue(RDF_Term.java:475)
        at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:244)
        at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:213)
        at org.apache.thrift.TUnion.write(TUnion.java:152)
        at org.apache.jena.riot.thrift.wire.RDF_Triple$RDF_TripleStandardScheme.write(RDF_Triple.java:524)
        at org.apache.jena.riot.thrift.wire.RDF_Triple$RDF_TripleStandardScheme.write(RDF_Triple.java:468)
        at org.apache.jena.riot.thrift.wire.RDF_Triple.write(RDF_Triple.java:397)
        at org.apache.jena.riot.thrift.wire.RDF_Term.standardSchemeWriteValue(RDF_Term.java:475)
        at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:244)
        at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:213)
        at org.apache.thrift.TUnion.write(TUnion.java:152)
        at org.apache.jena.tdb2.store.nodetable.NodeTableTRDF.writeNodeToTable(NodeTableTRDF.java:65)
        at org.apache.jena.tdb2.store.nodetable.NodeTableNative.accessIndex(NodeTableNative.java:146)
        at org.apache.jena.tdb2.store.nodetable.NodeTableNative._idForNode(NodeTableNative.java:118)
        at org.apache.jena.tdb2.store.nodetable.NodeTableNative.getAllocateNodeId(NodeTableNative.java:61)
        at org.apache.jena.tdb2.store.nodetable.NodeTableCache._idForNode(NodeTableCache.java:229)
        at org.apache.jena.tdb2.store.nodetable.NodeTableCache.getAllocateNodeId(NodeTableCache.java:146)
        at org.apache.jena.tdb2.store.nodetable.NodeTableWrapper.getAllocateNodeId(NodeTableWrapper.java:42)
        at org.apache.jena.tdb2.store.nodetable.NodeTableInline.getAllocateNodeId(NodeTableInline.java:49)
        at org.apache.jena.tdb2.loader.main.DataToTuples.idForNode(DataToTuples.java:219)
        at org.apache.jena.tdb2.loader.main.DataToTuples.nodes(DataToTuples.java:194)
        at org.apache.jena.tdb2.loader.main.DataToTuples.accTuples(DataToTuples.java:177)
        at org.apache.jena.tdb2.loader.main.DataToTuples.action(DataToTuples.java:138)
        at org.apache.jena.tdb2.loader.main.DataToTuples.lambda$startBulk$0(DataToTuples.java:112)
        at org.apache.jena.tdb2.loader.main.DataToTuples$$Lambda$279/0x00000008402af040.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
```

**Comment by GreenfishK** [comment]
solved with setting the JVM_ARGS variable in the docker image
