### ISSUE TITLE
Malformed BEARC query

### ISSUE THREAD

**Issue by GreenfishK** [GreenfishK/BEAR#8]
Malformed query: query10_q7_v0.txt

Stacktrace
```
Creating network "starvers_eval_default" with the default driver
Creating starvers_eval_evaluate_1 ... done
Attaching to starvers_eval_evaluate_1
evaluate_1            | /opt/graphdb/dist/bin/graphdb: line 75: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
evaluate_1            | Traceback (most recent call last):
evaluate_1            |   File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 926, in _query
evaluate_1            |     response = urlopener(request)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
evaluate_1            |     return opener.open(url, data, timeout)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
evaluate_1            |     response = meth(req, response)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
evaluate_1            |     response = self.parent.error(
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
evaluate_1            |     return self._call_chain(*args)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
evaluate_1            |     result = func(*args)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
evaluate_1            |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
evaluate_1            | urllib.error.HTTPError: HTTP Error 400: 
evaluate_1            | 
evaluate_1            | During handling of the above exception, another exception occurred:
evaluate_1            | 
evaluate_1            | Traceback (most recent call last):
evaluate_1            |   File "/starvers_eval/scripts/6_evaluate/query.py", line 187, in <module>
evaluate_1            |     result = engine.query()
evaluate_1            |   File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 960, in query
evaluate_1            |     return QueryResult(self._query())
evaluate_1            |   File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 930, in _query
evaluate_1            |     raise QueryBadFormed(e.read())
evaluate_1            | SPARQLWrapper.SPARQLExceptions.QueryBadFormed: QueryBadFormed: A bad request has been sent to the endpoint: probably the SPARQL query is badly formed. 
evaluate_1            | 
evaluate_1            | Response:
evaluate_1            | b'MALFORMED QUERY: Encountered " "order" "ORDER "" at line 17, column 1.\nWas expecting one of:\n    "(" ...\n    "{" ...\n    "}" ...\n    "[" ...\n    "." ...\n    <NIL> ...\n    <ANON> ...\n    "optional" ...\n    "graph" ...\n    "minus" ...\n    "filter" ...\n    "true" ...\n    "false" ...\n    "bind" ...\n    "service" ...\n    "values" ...\n    <Q_IRI_REF> ...\n    <PNAME_NS> ...\n    <PNAME_LN> ...\n    <BLANK_NODE_LABEL> ...\n    <VAR1> ...\n    <VAR2> ...\n    <INTEGER> ...\n    <INTEGER_POSITIVE> ...\n    <INTEGER_NEGATIVE> ...\n    <DECIMAL> ...\n    <DECIMAL_POSITIVE> ...\n    <DECIMAL_NEGATIVE> ...\n    <DOUBLE> ...\n    <DOUBLE_POSITIVE> ...\n    <DOUBLE_NEGATIVE> ...\n    <STRING_LITERAL1> ...\n    <STRING_LITERAL2> ...\n    <STRING_LITERAL_LONG1> ...\n    <STRING_LITERAL_LONG2> ...\n    "<<" ...\n    '
```

**Comment by GreenfishK** [comment]
The query looks like this 

```
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


SELECT * { 
    GRAPH <http://starvers_eval/ic/v0>
    {
        ?dataset rdf:type dcat:Dataset .
        ?dataset dc:title ?title .
        ?dataset dcat:distribution ?distribution .
        ?distribution dcat:accessURL ?URL .
        ?distribution dcat:mediaType ?mediaType .
        ?distribution dc:title ?filetitle .
        ?distribution dc:description ?description .
    }
    ORDER BY ?filetitle
    LIMIT 100 OFFSET 100
}
```
The problem is that the query template to generate the final queries does not work with the order by clause. The order by clause always needs to be on the outside.

**Comment by GreenfishK** [comment]
fixed issue by implementing function split_solution_modifiers_query(query)
