### ISSUE TITLE
Jena cannot load config file

### ISSUE THREAD

**Issue by GreenfishK** [GreenfishK/BEAR#9]
Stacktrace

```
evaluate_1            | cp: cannot stat '/starvers_eval/configs/jenatdb2_ic_sr_ng_bearc/*.ttl': No such file or directory
evaluate_1            | [2023-01-26 10:23:32] Server     INFO  Apache Jena Fuseki 4.0.0
evaluate_1            | [2023-01-26 10:23:32] Config     INFO  FUSEKI_HOME=/jena-fuseki
evaluate_1            | [2023-01-26 10:23:32] Config     INFO  FUSEKI_BASE=/run
evaluate_1            | [2023-01-26 10:23:32] Config     INFO  Shiro file: file:///run/shiro.ini
evaluate_1            | [2023-01-26 10:23:33] Server     INFO  System
evaluate_1            | [2023-01-26 10:23:33] Server     INFO    Memory: 90.0 GiB
evaluate_1            | [2023-01-26 10:23:33] Server     INFO    Java:   11.0.11
evaluate_1            | [2023-01-26 10:23:33] Server     INFO    OS:     Linux 5.15.0-52-generic amd64
evaluate_1            | [2023-01-26 10:23:33] Server     INFO    PID:    158
evaluate_1            | [2023-01-26 10:23:33] Server     INFO  Started 2023/01/26 10:23:33 UTC on port 3030
evaluate_1            | Traceback (most recent call last):
evaluate_1            |   File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 926, in _query
evaluate_1            |     response = urlopener(request)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
evaluate_1            |     return opener.open(url, data, timeout)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
evaluate_1            |     response = meth(req, response)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
evaluate_1            |     response = self.parent.error(
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
evaluate_1            |     return self._call_chain(*args)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
evaluate_1            |     result = func(*args)
evaluate_1            |   File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
evaluate_1            |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
evaluate_1            | urllib.error.HTTPError: HTTP Error 404: Not Found
evaluate_1            | 
evaluate_1            | During handling of the above exception, another exception occurred:
evaluate_1            | 
evaluate_1            | Traceback (most recent call last):
evaluate_1            |   File "/starvers_eval/scripts/6_evaluate/query.py", line 187, in <module>
evaluate_1            |     result = engine.query()
evaluate_1            |   File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 960, in query
evaluate_1            |     return QueryResult(self._query())
evaluate_1            |   File "/starvers_eval/python_venv/lib/python3.8/site-packages/SPARQLWrapper/Wrapper.py", line 932, in _query
evaluate_1            |     raise EndPointNotFound(e.read())
evaluate_1            | SPARQLWrapper.SPARQLExceptions.EndPointNotFound: EndPointNotFound: It was not possible to connect to the given endpoint: check it is correct. 
evaluate_1            | 
evaluate_1            | Response:
evaluate_1            | b'Error 404: Not Found\n'
```

**Comment by GreenfishK** [comment]
There was a wrong path to the config file in evaluate.sh.
